title: MobRetreat
url: https://www.mobretreat.org
repository: mobretreat/mobretreat-site
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-feed
exclude:
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CONTRIBUTING.md
  - scripts
  - test
  - yarn.lock
  - node_modules
  - README.md
include:
  - _redirects
sass:
    load_paths:
        - _sass
        - node_modules

